### ISSUE TITLE
libva error on ubuntu 18.10

### ISSUE THREAD

**Issue by naguirre** [knapsu/plex-media-player-appimage#19]
Hi  tried to launch :
- Plex_Media_Player_2.20.0.909-46413dd1_x64.AppImage
- Plex_Media_Player_20181003_46413dd1_x64.AppImage

On Ubuntu 18.10 and i get this error for both AppImage

```
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so has no function __vaDriverInit_0_32
libva info: va_openDriver() returns -1
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.
Aborted (core dumped)
```
Any idea ?

**Comment by probonopd** [comment]
Please run `LD_DEBUG=libs ./Plex_Media_Player_2.20.0.909-46413dd1_x64.AppImage` and watch for errors there.

**Comment by naguirre** [comment]
Please find the log attached.

[output.txt](https://github.com/knapsu/plex-media-player-appimage/files/2467516/output.txt)
I don't see more errors. I only found  __vaDriverInit_1_2 in i965_drv_video.so :

```
readelf -a  /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so | grep vaDriverInit
    82: 00000000000693c0  5048 FUNC    GLOBAL DEFAULT   12 __vaDriverInit_1_2
```

**Comment by knapsu** [comment]
I have no idea why GitHub does not notify me about new issues...
This is probabluy connected to excluding `libxcb*.so` from AppImage bundle. Did you try version **2.19**?

**Comment by flopon** [comment]
Same problem here.
We cannot use HW decoding on Ubuntu 18.04 because VA-API version is 1.1, and not 0.32 anymore

**Comment by probonopd** [comment]
What inside the AppImage calls VA-API?

**Comment by derzwen** [comment]
Same Problem here...

**Comment by probonopd** [comment]
Seems to be a known issue: https://github.com/intel/media-driver/issues/235#issue-341600240. The application is probably (and rightfully so) compiled against `i965_drv_video.so` that ships with Ubuntu 14.04, because this is currently the oldest still-supported distribution release. Unfortunately Intel seems to have broken backward binary compatibility since, which means that applications compiled against the old version of the Intel library will no longer run on newer systems that ship a newer version of the Intel library. 

I don't know what is the best cause of action here. Can we disable it altogether? Libraries that break backward compatibility are not something I am keen on supporting.

**Comment by knapsu** [comment]
Because of the mentioned driver incompatibilities I've disabled VA-API support on 2019-01-28. VDPAU hardware acceleration support is still enabled in PMP. If someone has VA-API driver he most certainly also has a VA-API -> VDPAU wrapper installed on his system for compatibility reasons.

Seems no one reported any problems with this approach for the last year. Closing the issue.
