### ISSUE TITLE
.desktop 'Uninstall' function doesn't work or populate correctly

### ISSUE THREAD

**Issue by Snowman3456** [knapsu/plex-media-player-appimage#6]
Shows up like this (also doesn't work):

![screenshot from 2018-01-24 23-10-17](https://user-images.githubusercontent.com/4528283/35370657-25c99ad8-015d-11e8-9b8a-cb9e95677cb7.png)

I think it should be like this:

```
[Desktop Action Uninstall]
Name=Uninstall
```

(This one definitely works anyway: https://github.com/Enigma0/build-scripts/blob/master/plexmediaplayer.desktop)

**Comment by knapsu** [comment]
Hi @Enigma0. Thanks for the detailed explanation.

You are right, the uninstall entry appears to be incorrectly created by `linuxdeployqt` or `appimagetool` that I use for AppImage build. Will check it and provide a patch upstream.

**Comment by Snowman3456** [comment]
If `Master` still isn't building for you, apparently `tv2` branch is there the new stuff is being worked on: https://github.com/plexinc/plex-media-player/issues/653#issuecomment-363896863

**Comment by probonopd** [comment]
@Enigma0 I don't see an "Uninstall" menu item in the screenshot you have posted - where is it? `appimaged` doesn't add a menu entry to the desktop file named "Uninstall".

**Comment by knapsu** [comment]
@probonopd the issue is with https://raw.githubusercontent.com/AppImage/AppImageKit/master/desktopintegration script that is downloaded by `get_desktopintegration` function in `functions.sh` helper script (https://github.com/AppImage/AppImages/blob/master/functions.sh).

It contains:
```
  # delete "Actions" entry and add an "Uninstall" action
  sed -i -e '/^Actions=/d' "$DESTINATION_DIR_DESKTOP/$VENDORPREFIX-$DESKTOPFILE_NAME"
  cat >> "$DESTINATION_DIR_DESKTOP/$VENDORPREFIX-$DESKTOPFILE_NAME" << EOF

Actions=Uninstall;

[Uninstall]
Name=Remove desktop integration for $APP_FULL
Exec="$APPIMAGE" --remove-appimage-desktop-integration

EOF
```
It should have `[Desktop Action Uninstall]` according to Desktop Entry Specification from freedesktop.

I cannot find this file in GitHub repository. Can you point me to it please. Is there any other more modern way of doing desktop integration?

**Comment by Snowman3456** [comment]
@probonopd The `Unnamed` item is presumably _supposed_ to be the `Uninstall `function but it isn't showing up correctly.

**Comment by probonopd** [comment]
Ah, that old `desktopintegration` script. I am not maintaining it anymore and advise users to use the optional `appimaged` daemon instead.
